name: Keep Render Alive

on:
  schedule:
    - cron: "*/10 * * * *" # every 10 minutes
  workflow_dispatch: # allows manual trigger too

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Curl Render App
        run: curl -s https://yt-shorts-downloader-backend-e5rw.onrender.com/ > /dev/null
